package helsinki.assets;

import ua.com.fielden.platform.entity.fetch.IFetchProvider;
import ua.com.fielden.platform.utils.EntityUtils;
import ua.com.fielden.platform.dao.IEntityDao;

/**
 * Companion object for entity {@link Asset}.
 *
 * @author Developers
 *
 */
public interface AssetCo extends IEntityDao<Asset> {
    static final String DEFAUL_KEY_VALUE = "Autogenerated";
    static final String ASSET_KEY_NAME = "ASSET NO";

    static final IFetchProvider<Asset> FETCH_PROVIDER = EntityUtils.fetch(Asset.class).with("number", "desc", "assetType");


}
